#!/usr/bin/env bash
# script to tx files from client to server.


PATH=$1
IP=$2
USR=$3
SSH_PATH=$4

if (($# -lt 3)); do
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no $USER@$IP:$PATH $USR@$SSH_PATH:~/
fi
