#!/usr/bin/env bash
# install nginx and setup

apt-get update
apt-get --yes install 'nginx'
echo 'Holberton School' > '/var/www/html/index.nginx-debian.html'
service nginx reload
service nginx restart
