#!/usr/bin/env bash
# install nginx and setup

apt-get install -y nginx
ufw allow 'Nginx HTTP'
touch /var/www/html/index.html
echo 'Holberton School' > /var/www/html/index.html
sudo service nginx reload
sudo service nginx reset
