#!/usr/bin/env bash
# 10. Fizzbuzz in Bash

declare -i i=1
while ((i < 101)); do
    if ((i % 15 == 0)); then
	echo "FizzBuzz"
    elif ((i % 5 == 0)); then
	echo "Buzz"
    elif ((i % 3 == 0)); then
	echo "Fizz"
    else
	echo $i
    fi
    ((i++))
done
