#!/usr/bin/env bash
# 12. Turn the passwd file into a silly story

while IFS=: read -r USERNAME PASSWORD USERID GROUPID UIF HOME COMMAND; do
    echo "The user $USERNAME is part of the $GROUPID gang, lives in $HOME and rides $COMMAND. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $UIF"
done < "/etc/passwd"
