#!/usr/bin/env bash
# 5. loop from 1 to 10 and display things at places.

i=1
while [ $i -lt 11 ]; do
    if [ $i -eq 4 ]; then
	echo "bad luck"
    elif [ $i -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((i++))
done
