#!/usr/bin/env bash
# 9. use if to print stuff about holbertonschool file.
# check 'help test' to see test stuff.

if [[ -a "holbertonschool" ]]; then
    echo "holbertonschool file exists"
    if [[ -s "holbertonschool" ]]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [[ -f "holbertonschool" ]]; then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
